// MicroPython version info
#define MICROPY_GIT_TAG "ESP32_LoBo_v2.0.2"
#define MICROPY_GIT_HASH "abcdef1"
#define MICROPY_BUILD_DATE "2017-09-19"
#define MICROPY_VERSION_MAJOR (2)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (2)
#define MICROPY_VERSION_STRING "2.0.2"
